[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "space-planner"

[services.variables]
NODE_ENV = "production"
PORT = "${{RAILWAY_PUBLIC_PORT}}"

[services.build]
buildCommand = "npm install"

[services.deploy]
startCommand = "npm start"
